---
title: "Code_Final_Project"
output: html_document
---

```{r}
# import necessary libraries
library(tidyverse)
library(shiny)
library(plotly)
library(ggnewscale) # allows for more complex plots

# import base data set
earnings = read.csv('Median Earnings.csv')

earnings
```
Things to clean:
1. Change Column Names
2. Typecast numbers to int
3. Decide if margin of errors want to be kept (might need to make it another column if so) + condense dataframe

```{r}
df <- earnings %>% 
  mutate(X = lag(X, n = 1, default = NA))

females <- df[, 38:ncol(df)] #gets only the columns for females

#adds some of the column names so that we can use the names function
females[3,10] <- "Science and Engineering Related Fields"
females[3,11] <- 'Business'
females[3,12] <- 'Education'
females[3,1] <- 'Total'

#combines the females with the states column
females <- cbind(df[,1], females)
females[3,1] <- 'States'
names(females) <- females[3,]

#gets only the rows and columns wihtout nas
females <- females[5:nrow(females),c(-3,-14)]

#you can change the by to get all of the errors instead
females <- females[seq(1, nrow(df), by = 3),] 

#parses the numbers for all of the columns
for (each in 2:ncol(females)) {
  females[,each] <- parse_number(females[,each])
}

#does the same thing but for males and all genders
males <- df[,20:37]
males[3,10] <- "Science and Engineering Related Fields"
males[3,11] <- 'Business'
males[3,12] <- 'Education'
males[3,1] <- 'Total'
males <- cbind(df[,1], males)
males[3,1] <- 'States'
names(males) <- males[3,]
males <- males[5:nrow(males),c(-3,-14)]
males <- males[seq(1, nrow(df), by = 3),]

for (each in 2:ncol(males)) {
  males[,each] <- parse_number(males[,each])
}

#this one had a lot of columns that were named the wrong thing, so I had to 
#check with the csv and overwrite them
all_gender <- df[,1:19]
all_gender[2,9] <- "Engineering"
all_gender[2,10] <- "Multidisciplinary Studies"
all_gender[2,11] <- "Science and Engineering Related Fields"
all_gender[2,12] <- 'Business'
all_gender[2,13] <- 'Education'
all_gender[2,1] <- 'States'
all_gender[2,2] <- 'Total'
all_gender[2,18] <- 'Communications'
names(all_gender) <- all_gender[2,]
all_gender <- all_gender[5:nrow(all_gender),c(-3,-14)]
all_gender <- all_gender[seq(1, nrow(df), by = 3),]

for (each in 2:ncol(all_gender)) {
  all_gender[,each] <- parse_number(all_gender[,each])
}

#if you want a full df

#adds a row for the gender identifier
females['Gender'] <- rep('female', nrow(females))
males['Gender'] <- rep('male', nrow(females))
all_gender['Gender'] <- rep('all', nrow(females))

#binds the rows
full_df <- rbind(females, males, all_gender)
na.omit(full_df) #gets rid of the two rows of nas


#could also merge on state or cbind
merged_df <- merge(females, males, by = 'States') #and you can merge more
```
```{r}
# removes unneeded data frames and variables to free up computer memory
rm(earnings)
rm(df)
rm(each)

# removes NA rows leftover while keeping in actual NA data
all_gender = all_gender[!is.na(all_gender$States),]
females = females[!is.na(females$States),]
males = males[!is.na(males$States),]
merged_df = merged_df[!is.na(merged_df$States),]
full_df = full_df[!is.na(full_df$States),]

# sorts all dataframes by state alphabetically
all_gender = all_gender[order(all_gender$States),]
females = females[order(females$States),]
males = males[order(males$States),]
full_df = full_df[order(full_df$States),]
merged_df = merged_df[order(merged_df$States),]

# reindexes every dataframe. By setting row names to NULL, it reindexes numerically
rownames(all_gender) = NULL
rownames(females) = NULL
rownames(males) = NULL
rownames(full_df) = NULL
rownames(merged_df) = NULL
```

```{r}
# Answering Question 1: What is the Gender Gap By Major Across The Country?

# diverging bar chart: https://r-charts.com/part-whole/diverging-bar-chart-ggplot2/
# Up is increase male, down is increase female. Likely won't be much down but that's the point
# show equal y-axis on both sides to exacerbate the difference
# group my major. Each bar represents a different major. Leave out Multidisciplinary studies due to NAs
# Allow grouped bars (dodge) to show up to 3(?) different states for comparison
# color by state?
# scale_fill_gradient by amount?
```

